apiVersion: v1
kind: Secret
metadata:
  name: manager-bootstrap-credentials
  namespace: system
type: Opaque
stringData:
  credentials.yaml: |-
    username: '${ICS_USERNAME}'
    password: '${ICS_PASSWORD}'
