# permissions for end users to view icsmachines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: icsmachine-viewer-role
rules:
  - apiGroups:
      - infrastructure.cluster.x-k8s.io
    resources:
      - icsmachines
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - infrastructure.cluster.x-k8s.io
    resources:
      - icsmachines/status
    verbs:
      - get
