# permissions for end users to view icsvms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: icsvm-viewer-role
rules:
  - apiGroups:
      - infrastructure.cluster.x-k8s.io
    resources:
      - icsvms
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - infrastructure.cluster.x-k8s.io
    resources:
      - icsvms/status
    verbs:
      - get
