# permissions for end users to edit icsvms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: icsvm-editor-role
rules:
  - apiGroups:
      - infrastructure.cluster.x-k8s.io
    resources:
      - icsvms
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - infrastructure.cluster.x-k8s.io
    resources:
      - icsvms/status
    verbs:
      - get
